CREATE TABLE cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    short_name VARCHAR(10) NOT NULL
);
CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    programming_language VARCHAR(255),
    city_id BIGINT REFERENCES cities(id)
);
CREATE INDEX idx_app_users_city ON app_users(city_id);
